name: ClearInventory
main: ltguide.ClearInventory.ClearInventory
version: 0.3
author: ltguide
description: Clears Inventory
commands:
  clearinventory:
    description: Clears Inventory
    usage: /<command> <main|bar|all>
    aliases: cinv