name: ClearInventory
main: ltguide.ClearInventory.ClearInventory
version: 0.2
commands:
  clearinventory:
    description: Clears Inventory
    usage: /clearinventory
  cinv:
    description: Clears Inventory
    usage: /cinv